name: Movie Bot Ultra Fast
on:
  schedule:
    - cron: '*/5 * * * *' # هەموو 5 خولەک جارێک خۆی بەخەبەر دێت
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests firebase-admin deep-translator
      - name: Run Ultra Sync
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python bot.py
